### PR TITLE
Add progress bar

### PR DESCRIPTION
**Pull request by Keiwen**
Quite new to Vue, but i loved toastr lib from codeseven, particularly progress bar.
It could be completed by adding checkbox on example page

### CODE REVIEW

**Comment by chengxulvtu** [comment]
@Keiwen  Nice.

**Comment by Keiwen** [comment]
Thanks, i'm waiting for next release to use it then ;)
Also could be nice to register here https://github.com/vuejs/awesome-vue, notifications section

**Comment by chengxulvtu** [comment]
@Keiwen  Already published.

**Comment by chengxulvtu** [comment]
@Keiwen Project  awesome-vue need english doc.

**Pull request merged**
